### ISSUE TITLE
hardcoding localhost url in solr - annotationContainer.php

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#97] opened 2017-02-16 22:28 UTC
https://github.com/digitalutsc/islandora_web_annotations/blob/7.x/includes/AnnotationContainer.php#L244

**Comment by MarcusBarnes** [comment] 2017-02-17 19:06
Closing this issue since this is not a bug.  Rather, the line pointed to above will use the value of the `islandora_solr_url` variable set in Solr URL field in  `admin > Islandora > Solr Index` configuration form.  The function `variable_get` allows you to set an optional default value if the value has not previously been set.   This is what is seen in the line [pointed to above](https://github.com/digitalutsc/islandora_web_annotations/issues/97#issue-208267911).   Please see  https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/variable_get/7.x for details.

Thank you for taking a close look at the code.

**Closed as completed by MarcusBarnes** 2017-02-17 19:06 UTC
Labels: bug
