### ISSUE TITLE
simultaneous createAnnotation triggers a conflict but also creates both annotations

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#164] opened 2017-04-18 20:02 UTC
When two users are creating annotations at the same time and saves their annotation, both annotations get created but one of them gets an error message and their annotation does not get added to the annotationcontainer.

Steps to reproduce
Set up your environment to allow two users to create annotations.
Both users go to a large image object to add an annotation to.
Both users need to create annotations and save their annotations at the same time on the same object.

Actual behaviour
Annotation is successfully created for one person, the other person gets a conflict warning and message that the annotation wasn't created, but the annotation still gets created. It however does not get added to the AnnotationContainer.

Expected behaviour
Both annotations should get created and added to the annotationcontainer.

**Comment by MarcusBarnes** [comment] 2017-04-20 15:36
We are currently not able to reproduce.  We are getting the expected behavior.  We'll close the issue for now.  If anyone encounters this again, please provide as many relevant details as possible and we'll reopen the issue and investigate further.  Thank you.

**Closed as completed by MarcusBarnes** 2017-04-20 15:36 UTC
