### ISSUE TITLE
Video annotation text should be normal

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_web_annotations#136] opened 2017-03-23 16:29 UTC
When video annotation is moused over and viewed, the text is italic.  Make it normal.

**Comment by Natkeeran** [comment] 2017-03-28 14:38
@kstapelfeldt I don't see the video annotations to be italic by default.  Please provide the steps to reproduce this issue.

**Comment by kstapelfeldt** [comment] 2017-04-05 14:37
Kirsta cannot reproduce on the newest version that we are testing for release. Closing for now.

**Closed as completed by kstapelfeldt** 2017-04-05 14:37 UTC
