### ISSUE TITLE
handling behaviour for deleting annotationContainers

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#237] opened 2017-11-20 22:11 UTC
on hogarth site
deleting annotations and annotationContainer and then create another annotation did not create a new annotationcontainer. The new annotation relates back to the deleted annotationContainer. The solr index did not update to remove the deleted annotationContainer.

**Comment by MarcusBarnes** [comment] 2017-11-20 22:17
Possibly related closed issue https://github.com/digitalutsc/islandora_web_annotations/issues/221.  We may have to reopen if this is still an issue.   @kimpham54 Did you delete the annotationContainer through accessing the object manage tab by finding the AnnotationCollection object in the Annotation Collection or did you delete directly from Fedora?

**Comment by kimpham54** [comment] 2017-11-21 13:50
I've done it both ways. from islandora it deleting the container deletes the annotations but it doesn't trigger solr. from fedora it doesn't delete the annotations and doesn't trigger solr. this is happening on the hogarth site

**Comment by MarcusBarnes** [comment] 2017-11-21 14:12
@kimpham54 Deleting from Fedora definitely wouldn't trigger a Solr update.  Deleting from the Islandora front-end should delete the annotationContainer properly based on #221 - this is where there could be something not functioning as expected.

**Comment by MarcusBarnes** [comment] 2017-11-21 16:33
Reviewing the Hogarth site, it appears that there has been some development work completed since Web Annotation was installed and updates were frozen for the semester.  @kimpham54 Would you be able to try reproduce this behaviour on a Islandra Vagrant VM using the latest from the default branch?   I believe that the pull-request that addressed issue #221 will probably delete the AnnotationContainer from the system (including Solr) when you delete it using the Islandora object manage interface (when accessing an object in the Annotation Collection).

**Comment by kimpham54** [comment] 2018-01-16 15:42
make sure to test in local

**Comment by MarcusBarnes** [comment] 2018-02-20 18:52
I've tested again using the release candidate code and this issue appears to be resolved in the latest code.  Once the Hogarth site is updated to use the most recent WA release the issue there should be resolved too.

**Closed as completed by MarcusBarnes** 2018-02-20 18:52 UTC
Labels: testing
