### ISSUE TITLE
simultaneous editing does not provide a conflict notice

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_web_annotations#165] opened 2017-04-18 20:40 UTC
When two users try to edit the same annotation in a large image object, the user whose edits could be saved does not receive an error message.

Steps to Reproduce
Assign two users to edit the same annotation in a large image object.
Have two users add edits, then synchronize the saving of an annotation at the same time.

Expected behaviour
For one user, the edits will be saved successfully. For the second user, a warning message would appear saying that there has been a conflict and edits could not be saved.

Ideally, there would be a locking mechanism that would prevent the second user from editing in the first place (and letting them know that someone else is currently editing the annotation).

Actual behaviour
For the first user, edits are saved successfully. No message is thrown back at the second user, their edits are not saved.

**Comment by MarcusBarnes** [comment] 2017-04-20 14:36
We are currently not able to reproduce.  We are getting the expected behavior.  We'll close the issue for now.  If anyone encounters this again, please provide as many relevant details as possible and we'll reopen the issue and investigate further.  Thank you.

**Comment by kimpham54** [comment] 2017-04-20 15:38
this is confirmed in Basic Image as well

**Comment by MarcusBarnes** [comment] 2017-04-20 20:18
Addressed in pull-request https://github.com/digitalutsc/islandora_web_annotations/pull/172 (merged with https://github.com/digitalutsc/islandora_web_annotations/commit/8a1f91198a3d8ec8ca27cdb2a7ca507363cc92f1).

**Closed as completed by MarcusBarnes** 2017-04-20 20:18 UTC
